version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord-py
    versions:
    - 1.7.0
  - dependency-name: isoncorrect
    versions:
    - 0.0.8
